package com.wz.dianping.dao;

import com.wz.dianping.model.shop;

public interface shopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sun Apr 09 11:22:30 HKT 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sun Apr 09 11:22:30 HKT 2023
     */
    int insert(shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sun Apr 09 11:22:30 HKT 2023
     */
    int insertSelective(shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sun Apr 09 11:22:30 HKT 2023
     */
    shop selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sun Apr 09 11:22:30 HKT 2023
     */
    int updateByPrimaryKeySelective(shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sun Apr 09 11:22:30 HKT 2023
     */
    int updateByPrimaryKey(shop record);
}